# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e92eb6170de6bbab4dc286811e38793164283a616f8a1562a0f2f1b6b21874966649593289ba1fab0f280d596900ff860ce5dfec42f4ccc032efa8749e40004c

test:
  secret_key_base: 7f5a687ef0a2bdbaeb45425156d980e8397c7d7bc15ccdb1e66858f5befb0051a84e56b4c8abae9a8b3e2ea59ef5fd6ef85b282e827bcf53e5d11303996b5cad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
